version: '3'

services:
  postgres:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_DB: retrofitdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/retrofit-data:/var/lib/postgresql/data
  retrofit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080